spring:
  main:
    log-startup-info: true
  application:
    name: sample-webapp-servlet

server:
  address: localhost
  port: 9100
  servlet:
    context-path: /samples/webapp-servlet/api
    
logging:
  level:
    mike.bootstrap: DEBUG
    mike.bootstrap.samples: DEBUG
    web: INFO

springdoc:
  swagger-ui:
    enabled: true
    display-request-duration: true
    path: /swagger-ui.html
    operationsSorter: alpha
    tagsSorter: alpha
    doc-expansion: list